### ISSUE TITLE
Have `generate_imbalanced_data` output `CategoricalVector`?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#50]
In the MLJ examples, at least, you're having to convert integer columns to `CategoricalVector`s. Is there a reason for not just generating `CategoricaVector` directly?

(Yes, in sklearn categoricals are usually integers. But this is a bad design choice in my opinion, because of the disappearance of classes under subsampling. In R, categoricals also have their own Factor type, and I think this a superior paradigm worth promoting more generally in Julia ML community.)

**Comment by EssamWisam** [comment]
@ablaom, If this is necessary then I may need to reimplement `generate_imbalanced_data` because I use matrices then convert to a table and as far as I know having mixed types there is not too efficient.

I think one can justify that this is somewhat okay because typically when categorical data is read from a file (what typically happens), if it's integers then they will have to coerce from count as in the example and if its strings they will have to coerce from textual. In other words, increasing familiarity with `ScientificTypes` is a good thing. What do you think?

**Comment by EssamWisam** [comment]
Another reason I am not with reimplementing is that I use it in tests while enforcing a matrix output so I don't want to go back to these.

**Comment by ablaom** [comment]
I stand by my original preference, but see you have some reasonable objections. Happy for you to make the call, as you better understand your overall needs.
