### ISSUE TITLE
On `input_scitype` for static models

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#76]
The meaning of `input_scitype` for `Static` models is not clear in the MLJ spec, a fact this is corrected [here](https://github.com/alan-turing-institute/MLJ.jl/blob/static-docs/docs/src/adding_models_for_general_use.md#static-models-models-that-do-not-generalize). My apologies for not catching this earlier, but now this is clarified, the implementation here is no longer compliant.

In the current package the `input_scitype` should refer to a bound on the `scitpe((X, y))` for `X` and `y` in `transform(model, _, X, y)`. So, for `SMOTE`, for example, I believe this should be

```
Tuple{
    Union{
        Table(Continuous), 
        AbstractMatrix{Continuous}},
    },
    AbstractVector
}
```

whereas it is currently 

```julia
Union{
    Table(Continuous),
    AbstractMatrix{Continuous}},
},
```

While fixing this is technically breaking, I think we can guarantee it actually breaks no existing code and can regard this a  bug fix.

**Comment by EssamWisam** [comment]
I see. Thank you so much for pointing this out. This definition of `input_scitype` indeed makes more sense for `transform` because `X` and `y` are just two inputs to transform without any assumed significance to `y`.

I could surely go over all models to fix this. Reading over the docs:

> A new trait, output_scitype, is for the output of transform

This implies that I ought to implement a similar change for `output_scitype`, eh?

Furthermore,
> The target_scitype refers to the output of predict, if implemented.

This suggests that I don't need (should remove?) the `target_scitype` from these static models, correct?

For reference, this is what I currently have for SMOTE:
```julia
MMI.metadata_model(
    SMOTE,
    input_scitype = Union{Table(Continuous),AbstractMatrix{Continuous}},
    output_scitype = Union{Table(Continuous),AbstractMatrix{Continuous}},
    target_scitype = AbstractVector,
    load_path = "Imbalance.MLJ.SMOTE"
)
```

**Comment by ablaom** [comment]
Yes, you are right on all counts. You should indeed also fix the `output_scitpye` along similar lines. And there is not need to implement `target_scitype`; the fallback `Unknown` is appropriate. 

Please flag me in the PR and I will review promptly.
