### ISSUE TITLE
SMOTENC document string

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#79]
From the doc-string for MLJ.SMOTENC:

```
 Transform Inputs
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

    •  X: A matrix or table of floats where each row is an observation from the dataset

    •  y: An abstract vector of labels (e.g., strings) that correspond to the
       observations in X
```
while we have 
```julia
julia> input_scitype(Imbalance.MLJ.SMOTENC)
Tuple{Table{<:AbstractVector{<:Union{Infinite, Finite}}}, AbstractVector}
```
suggesting:
 1. `X` can *not* be a matrix, and
 2. `X` *may* have columns with element scitype `<:Finite` (not just floats)

 contrary to doc-string.

**Comment by EssamWisam** [comment]
Yes, the float thing is incorrect (and the fact that a matrix is accepted); it's not synced with the docstring in `Imbalance.jl`. I will fix that. I will also check if there is any other type misinformation in MLJ specific docs for other methods.

Thank you bringing this up.

**Comment by EssamWisam** [comment]
As a sidenote, `RandomWalkOversampler` and `SMOTENC` are the only two methods that don't support matrix input for MLJ (because they require categorical columns to be flagged which the MLJ interface doesn't account for). I think adding that support shouldn't be hard and makes the package more consistent.
