### ISSUE TITLE
Other open questions (JOSS review 2)

### ISSUE THREAD

**Issue by ArneTillmann** [JuliaAI/Imbalance.jl#90]
1. Why do you use two different licenses (MIT for the code and reference CC BY 4.0 in the paper)? They do not differ much. For consistency I would use one for both.
2. Do you want to include the contributions page from the docs in the Github page?

**Comment by EssamWisam** [comment]
> Why do you use two different licenses (MIT for the code and reference CC BY 4.0 in the paper)? They do not differ much. For consistency I would use one for both.

So you're suggesting I can use MIT for both. Sure, will see how I can change that.

> Do you want to include the contributions page from the docs in the Github page?

If by the Github page, you mean the README, then as far as I believe it is included under `✨ Implemented Methods`

**Comment by ArneTillmann** [comment]
> So you're suggesting I can use MIT for both. Sure, will see how I can change that.

At least, I don't see a reason why you would want to use two different licenses. I am no expert on this topic. 

> If by the Github page, you mean the README, then as far as I believe it is included under ✨ Implemented Methods

I must have missed this.

**Comment by EssamWisam** [comment]
It may be the case that I didn't get to choose a license for the paper as I can't find that option in either the paper markdown or submission page. What confuses me is that MIT License seems to be defined as "a software license"; meanwhile, when I Googling `Can CC-BY-4.0 be used for software` seems to quickly suggest that the answer is no. 

Do you have any thoughts on this? Or would you think that it implies that it's okay for them to be different as these are different types of material? Otherwise, let me know if you have idea of how to change it for the paper.

Thank you.

**Comment by jbytecode** [comment]
Due to the JOSS submission 

https://github.com/openjournals/joss-reviews/issues/6310

**Comment by ArneTillmann** [comment]
I see. I didn't know they are both solely for different purposes.
